---
- name: Generate SSH Key pair
  hosts: localhost
  gather_facts: false
  become: true
  become_user: root
  vars:
    ansible_become_pass: 'j05ez05a'

  tasks:
    # Tarea: Verificar si la clave privada SSH ya existe
    - name: check if SSH private key exists
      ansible.builtin.stat:
        path: /root/.ssh/id_rsa
      register: ssh_key

    # Tarea: Crear par de claves SSH y forzar sobrescritura si ya existen
    - name: create SSH key pair
      ansible.builtin.command: ssh-keygen -t rsa -b 2048 -f /root/.ssh/id_rsa -N '' -q
      when: ssh_key.stat.exists == false or ssh_key.stat.islnk == true

    # Tarea: Establecer permisos para la clave privada SSH
    - name: set permissions for SSH private key
      ansible.builtin.file:
        path: /root/.ssh/id_rsa
        owner: root
        mode: '0600'
